name: Build WinCompose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Restore dependencies
        run: nuget restore src/wincompose.sln

      - name: Build project
        run: msbuild src/wincompose.sln /p:Configuration=Release

      - name: Run tests
        run: |
          # Add test command if needed

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wincompose-build
          path: ./bin/Release
