name: Build WinCompose

on:
  push:
    branches:
      - master  # Change from 'main' to 'master'
  pull_request:
    branches:
      - master  # Change from 'main' to 'master'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Build the project
      run: |
        cmake -S . -B build
        cmake --build build --config Release
