name: Build WinCompose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Restore dependencies
        run: nuget restore WinCompose.sln

      - name: Build project
        run: msbuild src/WinCompose.sln /p:Configuration=Release

      - name: Run tests
        run: |
          # Add test command if needed

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wincompose-build
          path: ./bin/Release
