name: Build WinCompose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake
        run: cmake -Bbuild -H.

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wincompose-build
          path: build/
