- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: '5.x'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    restoreSolution: 'src\wincompose.sln'
    feedsToUse: 'select'
    vstsFeed: 'your-feed-id'

- script: |
    nuget locals all -clear
  displayName: 'Clear NuGet Cache'
