name: Build WinCompose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Build the project
      run: |
        cmake -S . -B build
        cmake --build build --config Release
