name: Build and Deploy WinCompose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install .NET Framework 4.0 Developer Pack
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/msbuild/developerpacks" -OutFile "dotnet-framework-4.0-developer-pack.exe"
          Start-Process -FilePath "dotnet-framework-4.0-developer-pack.exe" -ArgumentList "/quiet /norestart" -Wait

      - name: Restore NuGet Packages
        run: nuget restore src/WinCompose.sln

      - name: Build WinCompose
        run: msbuild src/WinCompose.sln /p:Configuration=Release

      - name: Run Tests
        run: |
          cd src
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" tests\wincompose-tests.csproj /p:Configuration=Release

      - name: Create Installer
        run: |
          cd src
          msbuild src/installer/installer-helper.vcxproj /p:Configuration=Release
          
      - name: Deploy
        run: |
          # Deployment steps here
